# vim: ts=2:sts=2:sw=2:expandtab:smarttab:

publish:
  docker:
    tag:
      - latest
      - $$TAG
    repo: wachanga/slacker
    registry: registry.wachanga.com
    email: docker
    username: docker
    password: $$REGISTRY_PASSWORD


  docker:
    tag: latest
    repo: ontrif/slacker
    email: $$DOCKERHUB_EMAIL
    username: $$DOCKERHUB_USER
    password: $$DOCKERHUB_PASSWORD


  ssh:
    host: 85.143.166.213
    user: root
    commands:
      - docker pull registry.wachanga.com/wachanga/slacker
      - docker stop slacker
      - docker rm slacker

      - docker run
          -d --restart=always
          --name=slacker
          -v /etc/docker/containers/slacker:/etc/slacker
          -p 127.0.0.1:8025:8025
          registry.wachanga.com/wachanga/slacker
